-- Issue #44: a DataLab ratio is rescaled to 0-100 within one request alone (formats.md §NAVER DataLab).
-- Until now that request boundary could not be read off a row -- `terms` only audits a group's
-- search terms and carries no
-- startDate/endDate/timeUnit, so values of one group from different runs (different windows) were
-- indistinguishable.
-- request_key = the sha256 hex digest of the canonical JSON (json.dumps(sort_keys=True)) of the request body
-- actually sent (keywordGroups, startDate, endDate, timeUnit)
-- (collectors/naver/parsing.py:datalab_request_key).
-- Same parameters -> same key; move endDate by even a day (that window is rescaled) and the key differs.
-- The table has 0 rows (#44, coordinator check 2026-08-26), so no backfill is needed and this
-- goes straight to NOT NULL without a DEFAULT.
ALTER TABLE needs.naver_datalab_point ADD COLUMN request_key text NOT NULL;
