-- 021: a per-ruleset spare column on the aspect dictionary (fork issue #8).
--
-- One `aspect_lexicon` version houses several rulesets (`suncare-v2.2`, `p1-v2.2`, `shared`, and the
-- retrieval unit's `retrieval-topic` this issue brings in). A topic-dictionary row has to carry
-- three more facts than the seven shared columns have room for: an alias's script family
-- (ko|latin|mfds_inci), the topic type, and whether it is used in trend judgement. Putting those
-- on shared columns like `category` or `priority` would give one column a different meaning per
-- ruleset, so each ruleset gets its own column for its own vocabulary (the shape of
-- `labeled_set.extra`).
--
-- Existing rows stay `{}` and nothing on the reading side changes -- additive only.
ALTER TABLE needs.aspect_lexicon ADD COLUMN extra jsonb NOT NULL DEFAULT '{}'::jsonb;
