--
-- PostgreSQL database dump
--

\restrict S6uci60y2hMrorwfcqW7moYOwEbxNMeERsiV60azrZgiFHXeXeuhw0dddACF1kV

-- Dumped from database version 18.6 (Debian 18.6-1.pgdg13+2)
-- Dumped by pg_dump version 18.6 (Debian 18.6-1.pgdg13+2)

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET transaction_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

--
-- Name: trend_radar; Type: SCHEMA; Schema: -; Owner: -
--

CREATE SCHEMA trend_radar;


SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- Name: alembic_version; Type: TABLE; Schema: trend_radar; Owner: -
--

CREATE TABLE trend_radar.alembic_version (
    version_num character varying(32) NOT NULL
);


--
-- Name: fetch_log; Type: TABLE; Schema: trend_radar; Owner: -
--

CREATE TABLE trend_radar.fetch_log (
    id bigint NOT NULL,
    run_id uuid NOT NULL,
    at timestamp with time zone NOT NULL,
    source text NOT NULL,
    dataset text NOT NULL,
    url text NOT NULL,
    status integer,
    attempt integer NOT NULL,
    elapsed_ms integer,
    bytes integer,
    error text
);


--
-- Name: fetch_log_id_seq; Type: SEQUENCE; Schema: trend_radar; Owner: -
--

ALTER TABLE trend_radar.fetch_log ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME trend_radar.fetch_log_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: new_product; Type: TABLE; Schema: trend_radar; Owner: -
--

CREATE TABLE trend_radar.new_product (
    source text NOT NULL,
    product_key text NOT NULL,
    captured_at timestamp with time zone NOT NULL,
    name text NOT NULL,
    brand text,
    listed_at timestamp with time zone
);


--
-- Name: product; Type: TABLE; Schema: trend_radar; Owner: -
--

CREATE TABLE trend_radar.product (
    source text NOT NULL,
    product_key text NOT NULL,
    captured_at timestamp with time zone NOT NULL,
    name text NOT NULL,
    brand text,
    volume text,
    url text,
    ingredients text,
    first_seen_at timestamp with time zone NOT NULL,
    last_seen_at timestamp with time zone NOT NULL
);


--
-- Name: new_products_view; Type: VIEW; Schema: trend_radar; Owner: -
--

CREATE VIEW trend_radar.new_products_view AS
 SELECT source,
    product_key,
    name,
    brand,
    first_seen_at,
    last_seen_at
   FROM trend_radar.product p;


--
-- Name: price_point; Type: TABLE; Schema: trend_radar; Owner: -
--

CREATE TABLE trend_radar.price_point (
    source text NOT NULL,
    product_key text NOT NULL,
    captured_at timestamp with time zone NOT NULL,
    price integer NOT NULL,
    discount_rate integer
);


--
-- Name: rank_snapshot; Type: TABLE; Schema: trend_radar; Owner: -
--

CREATE TABLE trend_radar.rank_snapshot (
    source text NOT NULL,
    board text NOT NULL,
    category_key text NOT NULL,
    product_key text NOT NULL,
    captured_at timestamp with time zone NOT NULL,
    category_name text,
    rank integer NOT NULL,
    product_name text NOT NULL,
    brand text,
    price integer,
    discount_rate integer,
    review_count integer,
    review_rating double precision,
    rank_delta integer,
    is_new boolean
);


--
-- Name: COLUMN rank_snapshot.review_rating; Type: COMMENT; Schema: trend_radar; Owner: -
--

COMMENT ON COLUMN trend_radar.rank_snapshot.review_rating IS 'The rating the ranking row carried. Null means the ranking page does not publish one, not that the product is unrated -- for one source it arrives from the review service instead, in review_stats.';


--
-- Name: COLUMN rank_snapshot.rank_delta; Type: COMMENT; Schema: trend_radar; Owner: -
--

COMMENT ON COLUMN trend_radar.rank_snapshot.rank_delta IS 'Movement since the site''s previous ranking, where the site publishes one it computed. Null means not published, not zero -- one source''s was positive on every row and is deliberately dropped.';


--
-- Name: review; Type: TABLE; Schema: trend_radar; Owner: -
--

CREATE TABLE trend_radar.review (
    source text NOT NULL,
    review_key text NOT NULL,
    captured_at timestamp with time zone NOT NULL,
    product_key text NOT NULL,
    rating double precision,
    body text,
    author_hash text,
    written_at timestamp with time zone
);


--
-- Name: COLUMN review.author_hash; Type: COMMENT; Schema: trend_radar; Owner: -
--

COMMENT ON COLUMN trend_radar.review.author_hash IS 'A hash of the site''s author id. The id itself, the nickname, and everything else about the person are deliberately not stored.';


--
-- Name: review_answer; Type: TABLE; Schema: trend_radar; Owner: -
--

CREATE TABLE trend_radar.review_answer (
    source text NOT NULL,
    review_key text NOT NULL,
    question_key text NOT NULL,
    captured_at timestamp with time zone NOT NULL,
    product_key text NOT NULL,
    question_name text,
    answer text
);


--
-- Name: review_stats; Type: TABLE; Schema: trend_radar; Owner: -
--

CREATE TABLE trend_radar.review_stats (
    source text NOT NULL,
    product_key text NOT NULL,
    captured_at timestamp with time zone NOT NULL,
    review_count integer,
    rating_average double precision,
    pct_5 integer,
    pct_4 integer,
    pct_3 integer,
    pct_2 integer,
    pct_1 integer,
    positive_pct double precision,
    negative_pct double precision
);


--
-- Name: COLUMN review_stats.positive_pct; Type: COMMENT; Schema: trend_radar; Owner: -
--

COMMENT ON COLUMN trend_radar.review_stats.positive_pct IS 'The site''s own sentiment split over all of a product''s reviews. Null where the site publishes no such figure. Not comparable with review_topic.is_positive, which is ''most praised attribute''.';


--
-- Name: review_summary; Type: TABLE; Schema: trend_radar; Owner: -
--

CREATE TABLE trend_radar.review_summary (
    source text NOT NULL,
    product_key text NOT NULL,
    rank integer NOT NULL,
    captured_at timestamp with time zone NOT NULL,
    title text NOT NULL,
    body text
);


--
-- Name: review_topic; Type: TABLE; Schema: trend_radar; Owner: -
--

CREATE TABLE trend_radar.review_topic (
    source text NOT NULL,
    product_key text NOT NULL,
    topic_key text NOT NULL,
    captured_at timestamp with time zone NOT NULL,
    topic_name text NOT NULL,
    sentence text,
    is_positive boolean,
    score double precision,
    review_count integer,
    rank integer,
    topic_group text,
    share_pct integer
);


--
-- Name: COLUMN review_topic.is_positive; Type: COMMENT; Schema: trend_radar; Owner: -
--

COMMENT ON COLUMN trend_radar.review_topic.is_positive IS 'Whether the site presents this topic as praise. Always true for the source whose ranking surfaces praise only -- a ratio of this is not a sentiment measure.';


--
-- Name: COLUMN review_topic.score; Type: COMMENT; Schema: trend_radar; Owner: -
--

COMMENT ON COLUMN trend_radar.review_topic.score IS 'A site-specific weight. Deliberately not the same column as share_pct: a weight and a percentage are different units, and averaging them together would be wrong with nothing to show it.';


--
-- Name: COLUMN review_topic.share_pct; Type: COMMENT; Schema: trend_radar; Owner: -
--

COMMENT ON COLUMN trend_radar.review_topic.share_pct IS 'Share of survey respondents choosing this answer, within topic_group. Null for sources that publish a weight instead.';


--
-- Name: run; Type: TABLE; Schema: trend_radar; Owner: -
--

CREATE TABLE trend_radar.run (
    id uuid NOT NULL,
    captured_at timestamp with time zone NOT NULL,
    started_at timestamp with time zone NOT NULL,
    finished_at timestamp with time zone,
    status text NOT NULL,
    sources text NOT NULL,
    datasets text NOT NULL,
    note text,
    collector_version text,
    schema_revision text
);


--
-- Name: COLUMN run.collector_version; Type: COMMENT; Schema: trend_radar; Owner: -
--

COMMENT ON COLUMN trend_radar.run.collector_version IS 'The trend-radar version that produced this run''s rows. Null for runs recorded before 0009.';


--
-- Name: COLUMN run.schema_revision; Type: COMMENT; Schema: trend_radar; Owner: -
--

COMMENT ON COLUMN trend_radar.run.schema_revision IS 'The alembic revision this run wrote into. Null for runs recorded before 0009.';


--
-- Name: run_source; Type: TABLE; Schema: trend_radar; Owner: -
--

CREATE TABLE trend_radar.run_source (
    run_id uuid NOT NULL,
    source text NOT NULL,
    requests integer NOT NULL,
    records integer NOT NULL,
    retries integer NOT NULL,
    deduped integer NOT NULL,
    dropped_over_depth integer NOT NULL,
    budget_exhausted boolean NOT NULL,
    blocked_reason text,
    error_count integer NOT NULL,
    errors text,
    outcome text NOT NULL,
    configured_interval_s double precision,
    configured_concurrency integer,
    request_budget integer,
    final_interval_s double precision,
    final_concurrency integer,
    scope jsonb
);


--
-- Name: COLUMN run_source.scope; Type: COMMENT; Schema: trend_radar; Owner: -
--

COMMENT ON COLUMN trend_radar.run_source.scope IS 'How much of the site this run walked, as the source declared it, keyed by the dataset the run collected: {"review": {"boards": 1, ...}}. Compare two runs to tell a site that changed from a collector that did. Rows written before revision 0010 are flat and describe the whole source rather than the run.';


--
-- Name: alembic_version alembic_version_pkc; Type: CONSTRAINT; Schema: trend_radar; Owner: -
--

ALTER TABLE ONLY trend_radar.alembic_version
    ADD CONSTRAINT alembic_version_pkc PRIMARY KEY (version_num);


--
-- Name: fetch_log fetch_log_pkey; Type: CONSTRAINT; Schema: trend_radar; Owner: -
--

ALTER TABLE ONLY trend_radar.fetch_log
    ADD CONSTRAINT fetch_log_pkey PRIMARY KEY (id);


--
-- Name: new_product new_product_pkey; Type: CONSTRAINT; Schema: trend_radar; Owner: -
--

ALTER TABLE ONLY trend_radar.new_product
    ADD CONSTRAINT new_product_pkey PRIMARY KEY (source, product_key);


--
-- Name: price_point price_point_pkey; Type: CONSTRAINT; Schema: trend_radar; Owner: -
--

ALTER TABLE ONLY trend_radar.price_point
    ADD CONSTRAINT price_point_pkey PRIMARY KEY (source, product_key, captured_at);


--
-- Name: product product_pkey; Type: CONSTRAINT; Schema: trend_radar; Owner: -
--

ALTER TABLE ONLY trend_radar.product
    ADD CONSTRAINT product_pkey PRIMARY KEY (source, product_key);


--
-- Name: rank_snapshot rank_snapshot_pkey; Type: CONSTRAINT; Schema: trend_radar; Owner: -
--

ALTER TABLE ONLY trend_radar.rank_snapshot
    ADD CONSTRAINT rank_snapshot_pkey PRIMARY KEY (source, board, category_key, product_key, captured_at);


--
-- Name: review_answer review_answer_pkey; Type: CONSTRAINT; Schema: trend_radar; Owner: -
--

ALTER TABLE ONLY trend_radar.review_answer
    ADD CONSTRAINT review_answer_pkey PRIMARY KEY (source, review_key, question_key);


--
-- Name: review review_pkey; Type: CONSTRAINT; Schema: trend_radar; Owner: -
--

ALTER TABLE ONLY trend_radar.review
    ADD CONSTRAINT review_pkey PRIMARY KEY (source, review_key);


--
-- Name: review_stats review_stats_pkey; Type: CONSTRAINT; Schema: trend_radar; Owner: -
--

ALTER TABLE ONLY trend_radar.review_stats
    ADD CONSTRAINT review_stats_pkey PRIMARY KEY (source, product_key, captured_at);


--
-- Name: review_summary review_summary_pkey; Type: CONSTRAINT; Schema: trend_radar; Owner: -
--

ALTER TABLE ONLY trend_radar.review_summary
    ADD CONSTRAINT review_summary_pkey PRIMARY KEY (source, product_key, rank, captured_at);


--
-- Name: review_topic review_topic_pkey; Type: CONSTRAINT; Schema: trend_radar; Owner: -
--

ALTER TABLE ONLY trend_radar.review_topic
    ADD CONSTRAINT review_topic_pkey PRIMARY KEY (source, product_key, topic_key, captured_at);


--
-- Name: run run_pkey; Type: CONSTRAINT; Schema: trend_radar; Owner: -
--

ALTER TABLE ONLY trend_radar.run
    ADD CONSTRAINT run_pkey PRIMARY KEY (id);


--
-- Name: run_source run_source_pkey; Type: CONSTRAINT; Schema: trend_radar; Owner: -
--

ALTER TABLE ONLY trend_radar.run_source
    ADD CONSTRAINT run_source_pkey PRIMARY KEY (run_id, source);


--
-- Name: ix_fetch_log_run_at; Type: INDEX; Schema: trend_radar; Owner: -
--

CREATE INDEX ix_fetch_log_run_at ON trend_radar.fetch_log USING btree (run_id, at);


--
-- Name: ix_rank_snapshot_product_over_time; Type: INDEX; Schema: trend_radar; Owner: -
--

CREATE INDEX ix_rank_snapshot_product_over_time ON trend_radar.rank_snapshot USING btree (source, product_key, captured_at);


--
-- Name: ix_review_answer_product; Type: INDEX; Schema: trend_radar; Owner: -
--

CREATE INDEX ix_review_answer_product ON trend_radar.review_answer USING btree (source, product_key, question_key);


--
-- Name: ix_review_product; Type: INDEX; Schema: trend_radar; Owner: -
--

CREATE INDEX ix_review_product ON trend_radar.review USING btree (source, product_key);


--
-- Name: ix_review_topic_by_topic; Type: INDEX; Schema: trend_radar; Owner: -
--

CREATE INDEX ix_review_topic_by_topic ON trend_radar.review_topic USING btree (source, topic_key, captured_at);


--
-- Name: ix_run_captured_at; Type: INDEX; Schema: trend_radar; Owner: -
--

CREATE INDEX ix_run_captured_at ON trend_radar.run USING btree (captured_at);


--
-- Name: fetch_log fetch_log_run_id_fkey; Type: FK CONSTRAINT; Schema: trend_radar; Owner: -
--

ALTER TABLE ONLY trend_radar.fetch_log
    ADD CONSTRAINT fetch_log_run_id_fkey FOREIGN KEY (run_id) REFERENCES trend_radar.run(id) ON DELETE CASCADE;


--
-- Name: run_source run_source_run_id_fkey; Type: FK CONSTRAINT; Schema: trend_radar; Owner: -
--

ALTER TABLE ONLY trend_radar.run_source
    ADD CONSTRAINT run_source_run_id_fkey FOREIGN KEY (run_id) REFERENCES trend_radar.run(id) ON DELETE CASCADE;


--
-- PostgreSQL database dump complete
--

\unrestrict S6uci60y2hMrorwfcqW7moYOwEbxNMeERsiV60azrZgiFHXeXeuhw0dddACF1kV

